### ISSUE TITLE
Panic due to invalid index

### ISSUE THREAD

**Issue by mfelsche** [tremor-rs/tremor-language-server#162]
During development, while editing some trickle code, in a state where stuff doesnt compile i get multiple panics from the language server `v0.10.0` like this:

```
thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 18446744073709551615', src/lsp_utils.rs:59:55
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mfelsche** [comment]
This is the place where we use square bracket panicking array access 😱 :

https://github.com/tremor-rs/tremor-language-server/blob/main/src/lsp_utils.rs#L59

**Comment by Licenser** [comment]
fixed in connectors
